apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::675253838749:role/eksctl-brain-tasks-cluster-nodegro-NodeInstanceRole-oYuC8Oo9wV1K
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::675253838749:role/CodeBuildEKSRole
      username: codebuild
      groups:
      - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-23T10:52:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1281"
  uid: 7afcddeb-e289-417d-a9ce-89320ced3cbf